name: Export resume

on:
  push:
    branches:
      - main
  pull_request:
    brances:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install resume cli & build & export
        run: |
          set -x
          sudo chown -R $USER:$USER /usr/local
          npm install -g resume-cli
          npm install -g jsonresume-theme-elegant
          npm install -g jsonresume-theme-even
          npm install
          resume validate
          resume export index.html -t elegant
          resume export resume.pdf -t even
          git config --global user.name 'Tran Zha Github Actions'
          git config --global user.email 'trannzfsg@users.noreply.github.com'
          git checkout main
          git add .
          git commit -m "Github actions build resume index.html and resume.pdf"
          git push origin main
